### ISSUE TITLE
visual debug output for ML data

### ISSUE THREAD

**Issue by florian-grond** [Shared-Reality-Lab/IMAGE-server#117]
Task: implement a debug visualization for the ML output.
ML output of the IMAGE project is largely still a black box. It is often a challenging to relate output data with concrete elements and their extent in the image analyzed and hence it is difficult to interpret the quality of the audio rendering. To support the IMAGE development, we need a visual debug output, which means a simple graphical overlay over the web graphics that the ML has analyzed. This overlay needs to: draw rectangles around the objects, and indicate the centroid and what has been recognized, the same applies to the semantic segmentation output, where we need to visualize the outline of the segments, the centroid and what the segment represents. This debug output needs to be accessible through the browser extension, to evaluate the ML output and the audio rendering where it is produced.
The data structure of the debug output should also serve rendering needs on the haptic side.

**Comment by rohanakut** [comment]
After a discussion with @JRegimbal, we came to a common conclusion that this issue needs more clarity. Currently, the preprocessors supply the bounding boxes, segments and contours in a JSON format to the handlers. 

@jeffbl could you please clarify if there is any additional information required from the preprocessors?

**Comment by jeffbl** [comment]
Fair enough, thanks for raising. As mentioned in my comment on Sep20, this is ideally likely a handler, but its only purpose is to reflect the "raw" preprocessor data. My concern with moving this entirely over to the handler team is that as preprocessors are updated, the preprocessor team is the best positioned to keep this debug tool updated as well. That said, I also recognize that the expertise for writing handlers is really outside the preprocessor team. What about a proposed a split where the handler team (@JRegimbal) created an initial demonstration version, so handled all the schema and design work, then turned it over to the preprocessor team to flesh it out and keep it up-to-date with future preprocessor changes? Would that be the most efficient method given the current project skillsets, and a fair split? (@JRegimbal I completely understand that this may then be a longer-term item since you're very scheduled as well!) Happy to hear/discuss alternatives. One fallback would be to skip it being a handler, and just have the preprocessor dump jpegs on the server or something. I think that was discussed previously, since that approach would avoid all the handler/schema work entirely, at the cost of it being significantly less convenient for the developers using it.

**Comment by rohanakut** [comment]
@jeffbl I think a handler-preprocessor split seems like a more viable alternative. I believe dumping the images would not be scalable in the future unless we periodically delete the previously stored images or think of some alternative to prevent the accumulation of images.

**Comment by rohanakut** [comment]
@jeffbl are we proceeding with a handler-preprocessor split?

**Comment by jeffbl** [comment]
@rohanakut I am trying to brainstorm a way to have this involve @JRegimbal as little as possible since she needs to spend time on other priorities. Something like writing the images to a directory, and giving @florian-grond relatively easy access to that directory remotely. This would likely be enabled only on unicorn, since it is effectively an internal test system, at least for now, or otherwise gated so it would have to be turned on/off, so that it isn't doing this for all images in production (which would be a waste, and introduce other issues).

**Comment by florian-grond** [comment]
with the images, @jeffbl, you mean the preprocessor output? This will also be useful for the haptics team!

**Comment by jeffbl** [comment]
@florian-grond Yes, the debug info superimposed on the graphic itself. Still working out details of how you'll actually get it. It might be something like a directory of timestamped files that you'll be able to access through HTTP, and it may only get deployed on test server.

**Comment by jeffbl** [comment]
@rohanakut Note that @sriGanna and @rayanisran are working on similar functionality on the client side, so you should definitely sync up with them to make sure the three of you aren't repeating work. (see mentioned issue above from two weeks ago, but in speaking to them this morning, they are overlaying some preprocessor data over the graphic to show to the user in the extension.)

**Comment by jeffbl** [comment]
My proposal on this (in advance of discussion at tech-arch today) is:
New handler incorporates work by haptics team, just for debugging
When "Debug" option is checked in options, rendering from this handler is returned
Extension will need some method (e.g., a dropdown) to choose between "layers" representing different preprocessors (e.g., semseg vs object detector). This last can probably come later, since we only have those two right now, and it is easy to tell them apart visually?

**Comment by jeffbl** [comment]
After discussion, this will be implemented as follows:


New “debug layers” (final name TBD) rendering type implemented in extension
Handlers (not new preprocessors) create renderings based on preprocessor schema output. These contain the tagged SVG layers:

```
  rendering_name (e.g., “SVG debug: ca.mcgill.a11y.image.preprocessor.semanticSegmentation“)
    tag1 (e.g., "sky")
      SVG data (the outline(s) of this layer)
    tag2 (e.g., “trees”)
      SVG data (the outline(s) of this layer)
```

- If the capabilities section of the request contains the debug flag, then these debug handlers will check that flag, and only run if it is set. (This saves time on the server, and doesn’t bloat up the size of the renderings returned.)
- New debug renderings appear just as any other renderings in the existing interpretations list. Each will look like the debug window in Proposal #1, but there is no need for the “preprocessor” dropdown, since that information will be in the title of the rendering. (QUESTION: Can these be ordered in any useful way without doing a big hack?)

New work items created:

- @jaydeepsingh25 : create new rendering type in extension
- @JRegimbal : create new/update schemas
- @JRegimbal : create template handler
- @rohanakut : create handlers based on Juliette’s template handler for: existing grouped object detection output type (i.e., ca.mcgill.a11y.image.preprocessor.objectDetection) and semantic segmentation output type  (i.e., ca.mcgill.a11y.image.preprocessor.semanticSegmentation)
- Future: maps debug handler
- Future: charts debug handler

**Comment by jeffbl** [comment]
@JRegimbal @rohanakut @jaydeepsingh25 I propose "SVG visualization" for the name?

**Comment by rohanakut** [comment]
@jeffbl closing this issue as #439 , #440 , #441, #442 were created for solving this issue
