### ISSUE TITLE
Investigate Azure content tags for possible alternative to scene recognizer

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-server#225]
Determined today in meeting with @gp1702 that scene description might not be the best route but we're looking at content tags as an alternative.

_Originally posted by @Cybernide in https://github.com/Shared-Reality-Lab/auditory-haptic-graphics-server/issues/220#issuecomment-989287881_

Since we've nixed the scene recognizer, we need an alternative. Content tags might provide richer information that we can leverage for better contextual understanding. That being said, the tags that the model outputs are not necessarily the most useful ones and will require filtering. Tasks associated with this path:
- [ ] Find out what content tags Azure provides @gp1702
- [ ] Figure out which tags would be most useful from UX standpoint
- [ ] Combine that with confidence measures to create full-photo context description

**Comment by jeffbl** [comment]
From conversation with @Cybernide and @gp1702 this morning, when considering this, take into account how existing information and mechanisms, e.g., alt-text (keeping in mind not all graphics will have alt-text), factors in. This is not obvious, since some screen readers may have already spoken alt-text before the user asked for an IMAGE rendering. In this case, repeating this text in IMAGE may be redundant and annoying. This interaction may be too difficult to do automatically for now, but fallback could be some kind of explicit flag, where user can decide whether they want a general overview because that is lacking in their screenreader, but this approach seems clunky. Alternative alt-text generators may also be viable, but I don't know the state of the art on those services. (Our initial scene recognizer was problematic, for example)

**Comment by Cybernide** [comment]
Closing this issue as the scope of this issue is now encapsulated in #220
