### ISSUE TITLE
Create prototype OCR handler

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#329]
Although the eventual goal would be to intelligently integrate OCR results with those in other handlers, for an inititial experience, simply reading the blocks of text, perhaps with spatialization, would be a more achievable first step.

@Cybernide assigning to you to figure out UI/UX first step specifics with @BenMacnaughton and @aidanwilliams09 before it is assigned to them for implementation. After this is done, a new work item should be opened with a more integrated experience as well, on the assumption that won't make it into the initial version.

**Comment by Cybernide** [comment]
Just reiterating so we have record: I said as a first pass, saying "this picture contains this text: <text>" is sufficient. Afterwards, we will probably want to do some magic calculating the overlap between object centroids/segment bounds and character bounding boxes so that we can associate the words to the things.
