### ISSUE TITLE
OCR preprocessor: decide best cloud API & implement

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#428]
Capturing our conversation from a week or two ago:
The Azure service for individual pictures is based on older techniques, and doesn't seem to perform well, including issues like:
- angled text is not found
- background colors and contrast cause issues
- background colors that change under the text cause issues
- small text not found

Goal is to switch back to the original version of the Azure API, since performance seems to be better, but [optimize the wait loop better](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/383), then re-test using the test handler that outputs OCR as text, including [overlap with objects](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/388). Then we can decide how to integrate it with (for example) the photo handler.

**Comment by jeffbl** [comment]
Moving this to @jaydeepsingh25. Note that @BenMacnaughton and @aidanwilliams09 are still in the group slack if you have questions as you migrate this back. I'm also slipping this out two sprints given your other priorities.

**Comment by jaydeepsingh25** [comment]
@hongyec , can you please have a look into it?

**Comment by jeffbl** [comment]
Moving to next sprint due to @hongyec being busy, but hope to have completed by July5, since we're likely to have other dependencies on OCR we want to get done in the Jul18.

**Comment by jeffbl** [comment]
At this point, with the problems we've had with Azure OCR, I think we should also step back and also evaluate the possibility of using [Google's API](https://cloud.google.com/vision/docs/ocr).

**Comment by dafsgit** [comment]
As mentioned in the preprocessor's [README](https://github.com/Shared-Reality-Lab/IMAGE-server/blob/ocr-cloud-service-selection-feature/preprocessors/ocr/README.md#recommended-api), the 2 best APIs were Vision API and Read API.
I suggest Read API to be the default one because it gets the order of the words right and outputs less noise, as well as bounding boxes for complete sentences and not word for word.
The selection of this API should be done in the enviroment file for the OCR preprocessor, the rest of the code is already in the following pull request to be reviewed:

- #501

**Comment by jeffbl** [comment]
OK, once that is merged, I'm fine with Read API as the stake in the ground, and this can be closed. If needs to change in future, we can open a new work item/issue.

**Comment by dafsgit** [comment]
The pull request has been merged.

- #501
