### ISSUE TITLE
Create scripts for testing and expand dataset of graphics

### ISSUE THREAD

**Issue by rianadutta** [Shared-Reality-Lab/IMAGE-server#434]

**Comment by jeffbl** [comment]
Comments:
- for the 400 error you're getting (bad request), I suggest using `/var/docker/atp/bin/make_request` script on unicorn to get a valid request, and either then just use that directly from your script to make the request, or compare that output to your script's request to see where it is going wrong.
- I don't see any capability in `testdiff.py` for excluding certain fields that we won't care are different.
- I've added a few `#TODO:` comments in my PR with some other comments/feature additions
- I made some variables a bit more explicit - I only tested briefly, so please review before merging.
- The help should describe the options, much as the comments inside the script(s) do
- A nice tweak on `testset.py` might be to have it do a `testdiff.py` between new output and most recent timestamp, possibly implemented as a flag in `testdiff.py` that takes an image number, and just diffs the two latest timestamps, since that is likely to be a very common use case.

Please ping me when the actual requests are working, and I'll take another look. At that point, I'd say we can close this and handle further issues as separate work items.

**Comment by rianadutta** [comment]
Initial scripts are done.  Still need to implement TO DO items from comments and adding more capability.
