### ISSUE TITLE
Users reporting that IMAGE is failing on multi-line and multi-bar charts...

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-server#468]
... and we don't currently support them. Furthermore, @JRegimbal and I agree that it's perhaps somewhat misleading to allow this graphic type to be sent up to the server and have an unhelpful, general response. Given that we already have the code checking for the type of Highcharts chart, maybe we should have an error message saying something like "This Highcharts format isn't supported; we currently work on single line and single-series bar charts" etc

**Comment by JRegimbal** [comment]
The examples were on [this page](https://www.fao.org/state-of-fisheries-aquaculture/en/). It may be difficult to have an explanation generated in the server since there's not a uniform message for why renderings weren't produced, but doing something locally based on the type of request (graphic/map/chart) should be doable. That would mean keeping the explanation up to date with what's on the server though...maybe checking could be on the server and it could generate (part of) the message displayed?

**Comment by jeffbl** [comment]
I'm generally opposed to putting those smarts into the extension, since there are multiple cases where that could cause problems. For example, if someone else makes a preprocessor that handles that type, they would have to modify and deploy their own extension since otherwise they would never receive those highcharts formats. On the flip side, it isn't trivial to have preoprocessors all generating error messages in a generic way, and reporting them back to the user. For example, most end users probably don't care to see a report that the object detector couldn't find anything, unless perhaps no renderings are produced, when they might be curious why nothing was created.

Realistic options seem to be (please suggest others!)

1. Leave as-is, but make the error more descriptive (but still static)
2. Allow preprocessors to return "explanations" if they want, which are just text strings with a brief description of what happened. If no renderings are returned, we could display these as text by default, under the static error message. If all preprocessors created such strings, this could get long, and most might be uninteresting, since we'd just list all of them. However, then highcharts preprocessor could report back something like, "Highcharts preprocessor identified this as as a valid highcharts line chart, but cannot currently create a rendering since it contains multiple trendlines."
3. When page loads, query server to see if each map/chart is something that would return a rendering, and not put up a button if not. This is really not practical, since (a) we can't really know unless we try, so we'd likely have to run the entire pipeline anyway, and thus (b) just loading a page could generate multiple queries at once. The server load implications are frightening to consider.
4. Put the smarts to decide in the extension itself. I am very opposed to this idea, since to be sure, we'd have to replicate the entire server pipeline, and if we try and take shortcuts, they will require a separate design/implementation/debug process, and might not even work well anyway. Plus as mentioned above, they would have to assume a particular configuration of preprocessors on whatever server is in use, which could be a test server, or a server with a completely different configuration. I do not like this approach at all. Making this dynamic and flexible would be a significant undertaking.

Assigning to @Cybernide for pondering. Happy to discuss/brainstorm, since I do think we should do better than we're doing now...

**Comment by JRegimbal** [comment]
Agree with what you put @jeffbl, but I just want to clarify that there is no Highcharts preprocessor. This is all done in the handler as we have no intermediate format that could be a common interface for different chart data.

**Comment by jeffbl** [comment]
@JRegimbal true, but hopefully soon [charts will have a preprocessor](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/429)!

After discussion on Monday, take is to at least do the first option above as a stopgap until we do something better.

current (static) message for requests that IMAGE can't currently handle:

> IMAGE is unable to render this graphic. If you would like to let us know about this, please send a link to this graphic and a short description of the problem via email: [image@cim.mcgill.ca](mailto:%20image@cim.mcgill.ca) or report bugs using [our feedback form](chrome-extension://iimmeciildnckfmnpbhglofiahllkhop/feedback/feedback.html). Please ensure that the graphic you are sending contains no personal information.

@Cybernide I'm putting a draft in the google drive so we can collaboratively edit this text to get it into the build.

**Comment by JRegimbal** [comment]
@jeffbl that's true, I do think that for a future issue though that the handlers should be at least partly responsible for reporting why a rendering wasn't created. They are the components that make the renderings!

**Comment by jeffbl** [comment]
Good point. In eventual architecture, both preprocessors and handlers should be able to weigh in to the eventual messages. Note that at first, this might be something that could just show up in the logs, not exposed directly to end user. (I'm thinking like a summary of the key reason a rendering was/was not produced, any confidence info, etc.)

**Comment by Cybernide** [comment]
Suggested a few changes in the file

**Comment by jeffbl** [comment]
Revised error message, based on following goals:

- Emphasize using our feedback form for reporting things, not emailing
- Give common things that may prevent it from working
- Ideally, the message should come from the server and be settable, so that (for example) if we’re running different preprocessors on unicorn vs. pegasus, we could give different guidance. (e.g, if unicorn is in temporary use as a backup server, the message could indicate something like “because the main McGill IMAGE server is offline for maintenance, no OSM maps experiences can be produced” or whatever. Longer-term, this would also allow someone else running a server with a completely different set of preprocessors to have their own tweaked message. They could (should!) also remove the links to image@cim and our feedback form!

===
IMAGE is unable to render this graphic. If you would like to let us know about this, please use [our feedback form](GET LINK FROM CURRENT MESSAGE). If you are unable to use the form, you can also send a link to this graphic and a short description of the problem via email: [image@cim.mcgill.ca](mailto:image@cim.mcgill.ca). In either case, please ensure that the graphic you are sending contains no personal information.
There are some common issues that prevent IMAGE from being able to generate a rendering.

Graphic file : (for example, photographs including .jpg, .png, or .gif) Scenes containing only unusual or oddly framed objects, montages of separate pictures, highly stylized or hand-drawn graphics, and diagrams are not yet well supported by the machine learning tools, and may not produce any usable renderings.

Charts: We only support a subset of charts formatted with the [HighCharts](https://www.highcharts.com/) format. Currently, this means they can only be pie charts, or single-trend area or single-line charts. Further formats are under development.

Maps: Only maps where we can determine the latitude and longitude of the center of the map can generate renderings. If that location has no points of interest or streets nearby, IMAGE cannot generate any usable renderings.
===

Assigning to @Cybernide for final review. Please assign to Juliette when revised, for implementation.

**Comment by Cybernide** [comment]
Should we mention that we work only with embedded Google maps and are working on OSM support? Any reason why not?

**Comment by JRegimbal** [comment]
It may be worth specifying the embedded Google maps input if that's unlikely to change. OSM ways data and the new rendering for that are just enhancements and I'm not sure they're worth mentioning.

**Comment by jeffbl** [comment]
Not sure when that might change. We're starting to explore info. ouside direct google map embeds (https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/108), which I could see expanding outwards later if we can easily identify other map formats, or if we find particular sites that would be worth handling specifically. Generally, I'd lean toward more generic especially for maps/charts since you need to see the button to try getting a rendering anyway. I suppose if someone uses the context menu on a map graphic, then they might be confused. Suggest adding google maps as an example, rather than a restriction?

**Comment by jeffbl** [comment]
@Cybernide Please modify text above to final given your suggestion above, then assign to @JRegimbal for implementation.

@JRegimbal question: to implement this on server side, so that different servers could return different messages, if a new work item is required, please create so that we can triage.

**Comment by JRegimbal** [comment]
I'm confused...we want a hard coded message to be provided from the server when the server currently doesn't indicate a message? So really we want to change how both the orchestrator and extension works?

**Comment by jeffbl** [comment]
After discussion with @JRegimbal I've created #478 to move the static message to the server so that it can be changed on a per-server basis. @Cybernide after you update text, this should now to go to @jaydeepsingh25 so he can update the static message currently inside the browser extension.

**Comment by Cybernide** [comment]
=== BEGIN TEXT ===
IMAGE is unable to render this graphic. If you would like to let us know about this, please use [our feedback form](GET LINK FROM CURRENT MESSAGE). If you are unable to use the form, you can also send a link to this graphic and a short description of the problem via email: [image@cim.mcgill.ca](mailto:image@cim.mcgill.ca). In either case, please ensure that the graphic you are sending contains no personal information. There are some common issues that prevent IMAGE from being able to generate a rendering.

Graphic file : (for example, photographs including .jpg, .png, or .gif) Scenes containing only unusual or oddly framed objects, montages of separate pictures, highly stylized or hand-drawn graphics, and diagrams are not yet well supported by the machine learning tools, and may not produce any usable renderings.

 Charts: We only support a subset of charts formatted with the [HighCharts](https://www.highcharts.com/) format. Currently, this means they can only be pie charts, or single-trend area or single-line charts. Further formats are under development.

Maps: Only maps where we can determine the latitude and longitude of the center of the map can generate renderings. If that location has no points of interest or streets nearby, IMAGE cannot generate any usable renderings. Formats such as Google Maps and Open Street Maps usually work compared to other map formats given these requirements.

=== END TEXT ===

@jaydeepsingh25 please implement

**Comment by jeffbl** [comment]
Closing since this went into the now deployed 0.3.1 extension release. Note [minor text fix](https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/252) is still pending, and should go in for 0.3.2.
