### ISSUE TITLE
Remove Duplicate Intersections in OSM Output

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#507]
Duplicate intersections exist in OSM preprocessor output where entries are equivalent in terms of node ID, latitude, and longitude, but have slightly different `name` fields. For example the following are returned as separate entries in a `points_of_interest` field:

```json
{
    "id": 540192036,
    "lat": 46.4920905,
    "lon": -72.9606394,
    "cat": "intersection",
    "name": "Avenue Principale intersecting Rue Joseph-Garand"
}
```
```json
{
    "id": 540192036,
    "lat": 46.4920905,
    "lon": -72.9606394,
    "cat": "intersection",
    "name": "Rue Joseph-Garand intersecting Avenue Principale"
}
```

**Comment by samueljohnsegun148** [comment]
Okay thanks @JRegimbal. This duplicate type in particular was deliberately made to be so, with the idea to convey which street is intersecting the other based on the street being followed. For instance, if passing  through 'street A', and A is being intersected by street ' B', then the presentation would be A intersects B, and vice-versa. So the idea is that since A is named first, one would know that the current street being transversed is A and not B. However, now that it's clear that such would not be necessary, I will simply remove that to avoid the duplicate issue raised in a new PR. Thanks
