### ISSUE TITLE
STORY: As an accessibility researcher, I want to design a study so that I can determine the pros and cons of an object depth representation of photos for blind and low vision IMAGE users.

### ISSUE THREAD

**Issue by emmanuelwilson** [Shared-Reality-Lab/IMAGE-server#652]
- [x] Choose target publication venue
- [x] Clearly define hypothesis / contribution based on existing literature
- [x] Submit completed study template to Cyan

**Comment by jeffbl** [comment]
@emmanuelwilson suggest modification:

STORY: As an accessibility (haptics?) researcher, I want to design a study so that I can determine the pros and cons of an object depth representation of photos for blind and low vision IMAGE users.

Description (as discussed, don't need to break out into separate task work items, can just manage here if easier):
- [ ] Choose target publication venue
- [ ] Clearly define hypothesis / contribution based on existing literature
- [ ] Submit completed study template to Cyan
