### ISSUE TITLE
STORY: As a 2diy haptic experience developer, I want to characterize the limitations of the existing 2diy in reference to regions of texture, so that I can design useful experiences within current 2diy limitations.

### ISSUE THREAD

**Issue by LukeBebee** [Shared-Reality-Lab/IMAGE-server#793]
- [x]  Meet with Cyan to discuss our project trajectory in light of the 2diy technical issues. Should we look to work more with abstract experiences that may not require significant accuracy? Are texture mappings for photographs the best path?
- [ ]  Establish guidelines for aspects such as minimum region sizes, fineness of textures, etc.
- [ ]  Consider how we might parameterize these guidelines so that they could apply to other force feedback devices, including future 2diy versions from Haply.
- [ ]  Determine how to stay withing these guidelines with automated experience generation for photos on the 2diy.

**Comment by LukeBebee** [comment]
Not sure if this is the best title, so feel free to change it! Just wanted to make sure our goals for this sprint were outlined. Some of these tasks might not get completed and some of the development might get pushed as we have a large presentation for capstone soon!

**Comment by jeffbl** [comment]
I think you have three separate stories, which obviously won't all be this sprint. In order of curren priority:

STORY: As a handler developer, I want to create automatic texture mappings for common cases, so that experiences can be created for arbitrary photos.


STORY: As a 2diy haptic experience developer, I want to characterize the limitations of the existing 2diy in reference to regions of texture, so that I can design useful experiences within current 2diy limitations
- [ ]  Meet with Cyan to discuss our project trajectory in light of the 2diy technical issues. Should we look to work more with abstract experiences that may not require significant accuracy? Are texture mappings for photographs the best path?
- [ ] Establish guidelines for aspects such as minimum region sizes, fineness of textures, etc.
- [ ] Consider how we might parameterize these guidelines so that they could apply to other force feedback devices, including future 2diy versions from Haply.
- [ ] Determine how to stay withing these guidelines with automated experience generation for photos on the 2diy.


STORY: As a 2diy haptic experience developer, I want to brainstorm wildly different 2diy interactions for expressing photos, so that I can make sure we have adequately explored the design space.


Also, important to get your code into [the prototypes repo](https://github.com/Shared-Reality-Lab/IMAGE-prototypes) for safety and sharing!

**Comment by LukeBebee** [comment]
Remaining issues are being pushed to another story
